[build]
  functions = "netlify/functions"
[[redirects]]
  from = "/api/send"
  to = "/.netlify/functions/sendEmail"
  status = 200
  force = true
[[redirects]]
  from = "/api/authenticate"
  to = "/.netlify/functions/sendAuthenticate"
  status = 200
  force = true

